### ISSUE TITLE
The program disappears after running.

### ISSUE THREAD

**Issue by Eric20210907** [skanderhamdi/attention_cnn_lstm_covid_mel_spectrogram#1]
Hello, sir.All the files in the folder will disappear when I run the program.Why is this happening?Sincerely look forward to your reply.

**Comment by skanderhamdi** [comment]
Hello,
Please could you describe more? which files exactly?

**Comment by Eric20210907** [comment]
I think it may be a problem between lines 96 and 108 of the code, because this problem occurs when I run here.

**Comment by skanderhamdi** [comment]
Yes, effectively, you can ignore this section (from 96 to 108), because I've just used it to free memory and storage space

**Comment by Eric20210907** [comment]
Oh,I see!!!!Thank you very much~
